// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDflyp_nAG3KbZHNVQE42zsnXJoEakQCOM',
    appId: '1:131405688180:web:337db7bedabb8bb1fd5021',
    messagingSenderId: '131405688180',
    projectId: 'luzergia-solar-app',
    authDomain: 'luzergia-solar-app.firebaseapp.com',
    storageBucket: 'luzergia-solar-app.appspot.com',
    measurementId: 'G-DRVGB6V522',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0PP-b-IqI2ZZQ-yvUWQPzupv7atXqnyU',
    appId: '1:131405688180:android:01edbea4faacc53dfd5021',
    messagingSenderId: '131405688180',
    projectId: 'luzergia-solar-app',
    storageBucket: 'luzergia-solar-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJpOU5RhH2GW5J9cF4DN-BzCfjmT8bHVk',
    appId: '1:131405688180:ios:eda64ded2207fbcefd5021',
    messagingSenderId: '131405688180',
    projectId: 'luzergia-solar-app',
    storageBucket: 'luzergia-solar-app.appspot.com',
    iosBundleId: 'com.example.luzergiaSolarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJpOU5RhH2GW5J9cF4DN-BzCfjmT8bHVk',
    appId: '1:131405688180:ios:63765914ea628a92fd5021',
    messagingSenderId: '131405688180',
    projectId: 'luzergia-solar-app',
    storageBucket: 'luzergia-solar-app.appspot.com',
    iosBundleId: 'com.example.luzergiaSolarApp.RunnerTests',
  );
}
